### ISSUE TITLE
npm install with latest react fails

### ISSUE THREAD

**Issue by anandchakru** [react-native-masked-view/masked-view#107]
npm install --save @react-native-community/masked-view
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: dink001@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0" from @react-native-community/masked-view@0.1.10
npm ERR! node_modules/@react-native-community/masked-view
npm ERR!   @react-native-community/masked-view@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/njoynjami/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/njoynjami/.npm/_logs/2021-03-15T13_30_30_753Z-debug.log

**Comment by hussainahmad** [comment]
unable to start new project due to this

**Comment by sachin3072004** [comment]
Facing the same issue.

**Comment by MCKmecik** [comment]
Same problem here

**Comment by dezudas** [comment]
+1

**Comment by Matthewnie** [comment]
+1

**Comment by sherebiahtishbi** [comment]
Facing the same issue after upgrading to react 17. Any solution please? 

Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0" from @react-native-masked-view/masked-view@0.2.2
npm ERR! node_modules/@react-native-masked-view/masked-view
npm ERR!   @react-native-masked-view/masked-view@"*" from the root project

**Comment by sherebiahtishbi** [comment]
Seeing the slow response moved my project to 16.13.1.

**Comment by sachin3072004** [comment]
Moved back to 16.13.1 by making the following changes in the package.json.

"dependencies": {
     "react": "16.13.1",
    "react-native": "0.63.4",
}
"devDependencies": {
     "react-test-renderer": "16.13.1"
}

**Comment by rennehir** [comment]
While waiting for #108 to be published, we fixed the peer dependecy issue with pointing `react-native-community/masked-view` to the commit from the PR. Like this:
```json
{
  "dependencies": {
    "@react-native-community/masked-view": "https://github.com/react-native-masked-view/masked-view#a7a088dfffa9d4b35ee40aa3c5910126d442e90d",
  }
}
```

**Comment by FonDorn** [comment]
@react-native-masked-view/masked-view now is 0.2.3. Please use new version

**Comment by minh-dai** [comment]
With version 0.2.3, i can not install @react-navigation/stack, please recheck

**Comment by sachin3072004** [comment]
I am still seeing the following error.
ive-safe-area-context @react-native-community/masked-view
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: instagram@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0" from @react-native-community/masked-view@0.1.10
npm ERR! node_modules/@react-native-community/masked-view
npm ERR!   @react-native-community/masked-view@"*" from the root project

**Comment by Abe90** [comment]
> @react-native-masked-view/masked-view now is 0.2.3. Please use new version

Now there's a dependency problem with @react-navigation/stack

**Comment by SamarthSJ** [comment]
What I did is 
- removed note modules
- removed yarn.lock and npm.lock
- closed the project 
- restarted it
- installed node modules using yarn


and its worked for me
